import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

export default function Home(props) {
  console.log(props)
  /*const myFunction = async () => {
    let data = await fetch('https://api.bluelytics.com.ar/v2/latest')
    let res = await data.json()
    console.log(res)
    setDolarBluePrice(res.blue.value_buy)
  }; */

  /*useEffect( () => {
    myFunction()
  }, []) */

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>Dolar Blue ${props.resDolarPrice.blue.value_avg}</h2>
        <h2>Euro Blue ${props.resDolarPrice.blue_euro.value_avg}</h2>
        <h2>Bitcoin ${props.dataBitcoinPrice.data[0].quote.USD.price.toFixed()}</h2>
        <h2>Ethereum ${props.dataBitcoinPrice.data[1].quote.USD.price.toFixed()}</h2>
        <h2>BNB ${props.dataBitcoinPrice.data[4].quote.USD.price.toFixed()}</h2>
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  let dataDolarPrice = await fetch("https://api.bluelytics.com.ar/v2/latest");
  let resDolarPrice = await dataDolarPrice.json();

  let url =
      "https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest",
    qString ="?CMC_PRO_API_KEY=" +
      process.env.CMC_PRO_API_KEY +
      "&start=1&limit=5&convert=USD";

  const BitcoinPriceRes = await fetch(url + qString);
  const dataBitcoinPrice = await BitcoinPriceRes.json();
  return {
    props: { resDolarPrice, dataBitcoinPrice }, // will be passed to the page component as props
  };
}
