import Head from "next/head";
import styles from "../styles/Home.module.css";
import Home from "../components/Home";

export default function Index(props) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home props={props}/>

      <footer className={styles.footer}>
        <h6>Data provided by CoinGecko</h6>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  let dataDolarPrice = await fetch("https://api.bluelytics.com.ar/v2/latest");
  let resDolarPrice = await dataDolarPrice.json();

  const resCoingecko = await fetch("https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=1000&page=1&sparkline=false");
  const dataCoingecko = await resCoingecko.json()

  return {
    props: { resDolarPrice, dataCoingecko }, // will be passed to the page component as props
  };
}